using System;

namespace DigiStore.WebService.Application.DTOs
{
    public class FirmaBilgileriDto
    {
        public int AyarId { get; set; }
        public bool? KdvDahil { get; set; }
        public int? BirimId { get; set; }
        public string? Domain { get; set; }
        public DateTime? KayitTarihi { get; set; }
        public int? KdvOrani { get; set; }
        public string? MailServer { get; set; }
        public string? MailServerPort { get; set; }
        public string? MailUserName { get; set; }
        public string? MailPassword { get; set; }
        public string? facebook { get; set; }
        public string? twitter { get; set; }
        public string? instagram { get; set; }
        public string? Unvan { get; set; }
        public string? FBAppId { get; set; }
        public string? SegmentCariKodu { get; set; }
        public string? Telefon1 { get; set; }
        public string? Telefon2 { get; set; }
        public string? Adres { get; set; }
        public string? Mail { get; set; }
        public int? Ekleyen { get; set; }
        public int? Guncelleyen { get; set; }
        public DateTime? GuncellemeTarihi { get; set; }
        public string? OdemeYontemi { get; set; }
        public string? IyzicoAPIKey { get; set; }
        public string? IyzicoSecretKey { get; set; }
        public string? Title { get; set; }
        public int? BannerUrunId { get; set; }
        public string? InnovaKullaniciAdi { get; set; }
        public string? InnovaParola { get; set; }
        public int? FirmaKodu { get; set; }
        public int? Sirket_UyeId { get; set; }
        public bool? eFatura { get; set; }
        public int? AnonimMusteri { get; set; }
        public string? GondericiBirim { get; set; }
        public string? EArsivGondericiBirim { get; set; }
        public string? OnekEArsivNormal { get; set; }
        public string? OnekEArsivWeb { get; set; }
        public string? OnekEFatura { get; set; }
        public int? POSUyeId { get; set; }
        public bool? DonemGozuksunMu { get; set; }
        public bool? GarantiSanalPos { get; set; }
        public int? TeknikServisUrunId { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? TedarikciPosUyeId { get; set; }
        public bool? SatisTahsilati { get; set; }
        public bool? EksiStokOlsunMu { get; set; }
        public string? HBUserName { get; set; }
        public string? HBPassword { get; set; }
        public string? HBMerchantId { get; set; }
        public string? TYSaticiId { get; set; }
        public string? TYAPIKey { get; set; }
        public string? TYAPISecret { get; set; }
        public bool? OtomatikKurGuncelle { get; set; }
        public string? YKKullaniciGO { get; set; }
        public string? YKSifreGO { get; set; }
        public string? YKKullaniciAO { get; set; }
        public string? YKSifreAO { get; set; }
        public string? YKMusteriKodu { get; set; }
        public decimal? Yuvarlama { get; set; }
        public string? YKYazici { get; set; }
        public int? FaturaSatirSayisi { get; set; }
        public int? N11UyeId { get; set; }
        public int? HBUyeId { get; set; }
        public int? TYUyeId { get; set; }
        public int? GGUyeId { get; set; }
        public string? MetaDescription { get; set; }
        public string? MetaKeywords { get; set; }
        public bool? eIrsaliye { get; set; }
        public string? eIrsaliyeGondericiBirim { get; set; }
        public string? GSPMagazaNo { get; set; }
        public string? GSPAPIKullanici { get; set; }
        public string? GSPSifre { get; set; }
        public string? GSPHexAnahtar { get; set; }
        public string? GSPTerminalNo { get; set; }
        public string? GGDeveloperId { get; set; }
        public string? GGRoleName { get; set; }
        public string? GGRolePassword { get; set; }
        public string? GGAPIKey { get; set; }
        public string? GGSecretKey { get; set; }
        public string? Adres2 { get; set; }
        public string? Adres3 { get; set; }
        public string? youtube { get; set; }
        public string? pinterest { get; set; }
        public string? ParamClientCode { get; set; }
        public string? ParamClientUserName { get; set; }
        public string? ParamClientPassword { get; set; }
        public string? ParamClientGUID { get; set; }
        public int? ParamPosUyeId { get; set; }
        public int? IyzicoUyeId { get; set; }
        public int? SanalPosId { get; set; }
        public bool? B2Bv2 { get; set; }
        public string? SegmentOndalikAyraci { get; set; }
        public string? B2BGirisBaslik { get; set; }
        public string? B2BGirisAciklama { get; set; }
        public string? GoogleMapLink { get; set; }
        public bool? B2BKDVDahil { get; set; }
        public bool? B2BAcikSite { get; set; }
        public string? B2CGirisBaslik { get; set; }
        public string? B2CGirisAciklama { get; set; }
        public string? SKKullanici { get; set; }
        public string? SKSifre { get; set; }
        public string? GoogleMapLinkB2C { get; set; }
        public string? ReCaptchaProjectId { get; set; }
        public string? ReCaptchaSiteKey { get; set; }
        public bool? B2Cv2 { get; set; }
        public string? B2CDomain { get; set; }
        public string? B2CMailServer { get; set; }
        public string? B2CMailServerPort { get; set; }
        public string? B2CMailUserName { get; set; }
        public string? B2CMailPassword { get; set; }
        public string? B2CFacebook { get; set; }
        public string? B2CTwitter { get; set; }
        public string? B2CInstagram { get; set; }
        public string? B2CTelefon1 { get; set; }
        public string? B2CTelefon2 { get; set; }
        public string? B2CAdres { get; set; }
        public string? B2CMail { get; set; }
        public string? B2CTitle { get; set; }
        public string? B2CAdres2 { get; set; }
        public string? B2CAdres3 { get; set; }
        public string? B2CYoutube { get; set; }
        public string? B2CPinterest { get; set; }
        public string? B2CMetaDescription { get; set; }
        public string? B2CMetaKeywords { get; set; }
        public string? B2CUnvan { get; set; }
        public string? B2CFBAppId { get; set; }
        public string? OzanApiKey { get; set; }
        public string? OzanSecretKey { get; set; }
        public int? OzanPosUyeId { get; set; }
        public int? PayTrUyeId { get; set; }
        public string? PayTrMerchantId { get; set; }
        public string? PayTrMerchantKey { get; set; }
        public string? PayTrMerchantSalt { get; set; }
        public string? B2BFtpUserName { get; set; }
        public string? B2BFtpPassword { get; set; }
        public string? B2CFtpUserName { get; set; }
        public string? B2CFtpPassword { get; set; }
    }
}
